Repository e-m-b-a/embark, pull requests merged in 2021-09, with the labels that each got.

#4 favicon, exception
  check_project.sh
  embark/static/scripts/embaServiceDashboard.js
  embark/static/scripts/mainDashboard.js
  embark/templates/uploader/home.html
  embark/uploader/boundedexecutor.py
Labels: bug

#5 EMBA dev mode is default in EMBArk
  README.md
  embark/uploader/forms.py
  embark/uploader/models.py
  embark/uploader/test_models.py
  installer.sh
Labels: bug, enhancement

#7 Redesign and cleanup
  .gitignore
  README.md
  embark/static/content/css/fileUpload.css
  embark/static/content/css/globalStyle.css
  embark/static/content/css/home.css
  embark/static/content/css/individualReportDashboard.css
  embark/static/content/css/log.css
  embark/static/content/css/login.css
  embark/static/content/css/mainDashboard.css
  embark/static/content/css/navigation.css
  embark/static/content/css/reportDashboard.css
  embark/static/content/css/serviceDashboard.css
  embark/static/content/images/Embark_black.png
  embark/static/content/images/Embark_red.png
  embark/static/content/images/Embark_red_cropped.png
  embark/static/content/images/bg.png
  embark/static/content/images/bg.svg
  embark/static/content/images/embark_logo.svg
  embark/static/content/images/embark_logo_text.png
  embark/static/content/images/embark_logo_text.svg
  embark/static/content/images/favicon.png
  embark/static/content/images/fileUpload.jpg
  embark/static/content/images/header.png
  embark/static/scripts/alertBox.js
  embark/static/scripts/fileUpload.js
  embark/static/scripts/main.js
  embark/static/scripts/serviceDashboard.js
  embark/templates/uploader/about.html
  embark/templates/uploader/base.html
  embark/templates/uploader/embaServiceDashboard.html
  embark/templates/uploader/fileUpload.html
  embark/templates/uploader/home.html
  embark/templates/uploader/individualReportDashboard.html
  embark/templates/uploader/log.html
  embark/templates/uploader/login.html
  embark/templates/uploader/mainDashboard.html
  embark/templates/uploader/navigation.html
  embark/templates/uploader/progress.html
  embark/templates/uploader/reportDashboard.html
  embark/templates/uploader/reports.html
  embark/templates/uploader/searchBar.html
  embark/templates/uploader/serviceDashboard.html
  embark/uploader/urls.py
  embark/uploader/views.py
  installer.sh
Labels: enhancement
