Repository e-m-b-a/embark, pull requests merged in 2023-10, with the labels that each got.

#158 Feature/log viewer
  .gitignore
  Pipfile
  Pipfile.lock
  embark/dashboard/urls.py
  embark/dashboard/views.py
  embark/embark/consumers.py
  embark/embark/logviewer.py
  embark/embark/routing.py
  embark/embark/tests/__init__.py
  embark/embark/tests/test_linecache.py
  embark/static/content/css/logviewer.css
  embark/static/scripts/logViewer.js
  embark/static/scripts/serviceDashboard.js
  embark/templates/dashboard/logViewer.html
  embark/templates/dashboard/reportDashboard.html
  installer.sh
Labels: enhancement, EMBArk

#159 add MySQL LDFLAGS
  installer.sh
Labels: bug, Installation, EMBArk

#160 Backup-fix
  .gitignore
  export-DB.sh
  import-DB.sh
  installer.sh
Labels: bug, EMBArk
